-- VHDL Entity audiotest_lib.addrdecodewritedev.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:04:03 03/13/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;
USE ieee.math_real.all;
USE ieee.numeric_std.all;

ENTITY addrdecodewritedev IS
   PORT( 
      addr           : IN     boolean_vector (15 DOWNTO 0);
      clk            : IN     std_logic;
      cpuIRQ         : IN     std_logic;
      cpuNMI         : IN     std_logic;
      cpuRES         : IN     std_logic;
      data           : IN     std_logic_vector (7 DOWNTO 0);
      res_n          : IN     std_logic;
      wr             : IN     boolean;
      apuwr          : OUT    boolean;
      bkswwr         : OUT    boolean;
      controlportwr  : OUT    boolean;
      n163wr         : OUT    boolean;
      overlayvectors : OUT    boolean;
      ratetimerwr    : OUT    boolean;
      songramwr      : OUT    boolean;
      vectorramwr    : OUT    boolean;
      vrc6addr       : OUT    boolean_vector (3 DOWNTO 0);
      vrc6wr         : OUT    boolean
   );

-- Declarations

END addrdecodewritedev ;

