-- VHDL Entity audiotest_lib.addrdecodereadmem.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 16:09:07 02/12/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY addrdecodereadmem IS
   PORT( 
      addr              : IN     boolean_vector (15 DOWNTO 0);
      bootRAMdata       : IN     boolean_vector (7 DOWNTO 0);
      clk               : IN     std_logic;
      highsysramdataout : IN     boolean_vector (7 DOWNTO 0);
      lowsysramdataout  : IN     boolean_vector (7 DOWNTO 0);
      overlayvectors    : IN     boolean;
      rd                : IN     boolean;
      res_n             : IN     std_logic;
      songRAMdata       : IN     boolean_vector (7 DOWNTO 0);
      vectorRAMdata     : IN     boolean_vector (7 DOWNTO 0);
      wr                : IN     boolean;
      accesswait        : OUT    std_logic;
      bootRAMwr         : OUT    std_logic;
      highsysramwr      : OUT    boolean;
      lowsysramwr       : OUT    boolean;
      memdatain         : OUT    boolean_byte;
      data              : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END addrdecodereadmem ;

