-- VHDL Entity audiotest_lib.addrdecodereaddev.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 15:40:31 03/08/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;
USE ieee.math_real.all;
USE ieee.numeric_std.all;

ENTITY addrdecodereaddev IS
   PORT( 
      addr          : IN     boolean_vector (15 DOWNTO 0);
      rd            : IN     boolean;
      apurd         : OUT    boolean;
      controlportrd : OUT    boolean;
      memrd         : OUT    boolean;
      n163rd        : OUT    boolean;
      vrc6rd        : OUT    boolean
   );

-- Declarations

END addrdecodereaddev ;

