-- VHDL Entity audiotest_lib.apumixer.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:13:21 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY apumixer IS
   PORT( 
      dmcmix   : IN     boolean_vector (6 DOWNTO 0);
      noisemix : IN     boolean_vector (3 DOWNTO 0);
      p1mix    : IN     boolean_vector (3 DOWNTO 0);
      p2mix    : IN     boolean_vector (3 DOWNTO 0);
      trimix   : IN     boolean_vector (3 DOWNTO 0);
      mix      : OUT    boolean_vector (7 DOWNTO 0)
   );

-- Declarations

END apumixer ;

