-- VHDL Entity audiotest_lib.apustatusandaddrdec.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:15:26 02/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY apustatusandaddrdec IS
   PORT( 
      addr              : IN     boolean_vector (4 DOWNTO 0);
      clk               : IN     std_logic;
      cpuclk            : IN     boolean;
      dmcirq            : IN     boolean;
      frameint          : IN     boolean;
      noiseleniszero    : IN     boolean;
      p1leniszero       : IN     boolean;
      p2leniszero       : IN     boolean;
      playingsample     : IN     boolean;
      rd                : IN     boolean;
      res_n             : IN     std_logic;
      triiszero         : IN     boolean;
      wr                : IN     boolean;
      addrlow2          : OUT    boolean_vector (1 DOWNTO 0);
      dmcclearintflag   : OUT    boolean;
      dmcenabled        : OUT    boolean;
      dmcwr             : OUT    boolean;
      frctrclearintflag : OUT    boolean;
      genint            : OUT    boolean;
      irq               : OUT    boolean;
      mode              : OUT    boolean;
      noiseenabled      : OUT    boolean;
      noisewr           : OUT    boolean;
      p1enabled         : OUT    boolean;
      p1wr              : OUT    boolean;
      p2enabled         : OUT    boolean;
      p2wr              : OUT    boolean;
      resctr            : OUT    boolean;
      trienabled        : OUT    boolean;
      triwr             : OUT    boolean;
      wrdata            : OUT    boolean_vector (7 DOWNTO 0);
      data              : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END apustatusandaddrdec ;

