-- VHDL Entity audiotest_lib.audiotestmain.interface
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 13:15:47 12/19/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;

ENTITY audiotestmain IS
   PORT( 
      clk           : IN     std_logic;
      res_n         : IN     std_logic;
      SSM2603_bclk  : OUT    STD_LOGIC;
      SSM2603_cclk  : OUT    STD_LOGIC;
      SSM2603_pbdat : OUT    STD_LOGIC;
      SSM2603_pblrc : OUT    STD_LOGIC;
      ack_error     : OUT    STD_LOGIC;
      SSM2603_scl   : INOUT  STD_LOGIC;
      SSM2603_sda   : INOUT  STD_LOGIC
   );

-- Declarations

END audiotestmain ;

