--
-- VHDL Architecture audiotest_lib.audiotestmain.struct
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 13:15:47 12/19/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.numeric_std.all;
LIBRARY altera_lnsim;
USE altera_lnsim.altera_lnsim_components.all;
LIBRARY altera_mf; USE altera_mf.altera_mf_components.all;
USE ieee.std_logic_unsigned.all;

LIBRARY audiotest_lib;

ARCHITECTURE struct OF audiotestmain IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL I2Cstarttransfer : STD_LOGIC;
   SIGNAL addr             : std_logic_vector(6 DOWNTO 0);
   SIGNAL busy             : STD_LOGIC;
   SIGNAL data_wr          : std_logic_vector(7 DOWNTO 0);
   SIGNAL ena              : std_logic;
   SIGNAL error            : std_logic;
   SIGNAL l_data_tx        : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL leftadcvol       : STD_LOGIC_VECTOR(5 DOWNTO 0);
   SIGNAL leftdacvol       : STD_LOGIC_VECTOR(6 DOWNTO 0);
   SIGNAL r_data_tx        : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL ready            : STD_LOGIC;
   SIGNAL regaddr          : std_logic_vector(6 DOWNTO 0);
   SIGNAL regdata          : std_logic_vector(8 DOWNTO 0);
   SIGNAL res              : std_logic := '0';
   SIGNAL rightadcvol      : STD_LOGIC_VECTOR(5 DOWNTO 0);
   SIGNAL rightdacvol      : STD_LOGIC_VECTOR(6 DOWNTO 0);
   SIGNAL rw1              : STD_LOGIC;
   SIGNAL sampletick       : std_logic;
   SIGNAL sd_rx            : STD_LOGIC;
   SIGNAL update           : STD_LOGIC;
   SIGNAL voltick          : std_logic;
   SIGNAL writedone        : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL SSM2603_cclk_internal : STD_LOGIC;
   SIGNAL ack_error_internal    : STD_LOGIC;


   -- Component Declarations
   COMPONENT SSM2603regwriter
   PORT (
      I2Cbusy   : IN     std_logic ;
      clk       : IN     std_logic ;
      regaddr   : IN     std_logic_vector (6 DOWNTO 0);
      regdata   : IN     std_logic_vector (8 DOWNTO 0);
      res_n     : IN     std_logic ;
      setreg    : IN     std_logic ;
      addr      : OUT    std_logic_vector (6 DOWNTO 0);
      data_wr   : OUT    std_logic_vector (7 DOWNTO 0);
      ena       : OUT    std_logic ;
      rw        : OUT    std_logic ;
      writedone : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT codecsetup
   PORT (
      ack_error        : IN     STD_LOGIC ;
      clk              : IN     std_logic ;
      leftadcvol       : IN     STD_LOGIC_VECTOR (5 DOWNTO 0);
      leftdacvol       : IN     STD_LOGIC_VECTOR (6 DOWNTO 0);
      res_n            : IN     std_logic ;
      rightadcvol      : IN     STD_LOGIC_VECTOR (5 DOWNTO 0);
      rightdacvol      : IN     STD_LOGIC_VECTOR (6 DOWNTO 0);
      update           : IN     STD_LOGIC ;
      writedone        : IN     std_logic ;
      I2Cstarttransfer : OUT    STD_LOGIC ;
      error            : OUT    std_logic ;
      ready            : OUT    STD_LOGIC ;
      regaddr          : OUT    std_logic_vector (6 DOWNTO 0);
      regdata          : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT i2c_master
   GENERIC (
      input_clk : INTEGER := 50_000_000;      --input clock speed from user logic in Hz
      bus_clk   : INTEGER := 400_000
   );
   PORT (
      addr      : IN     STD_LOGIC_VECTOR (6 DOWNTO 0);
      clk       : IN     STD_LOGIC;
      data_wr   : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);
      ena       : IN     STD_LOGIC;
      reset_n   : IN     STD_LOGIC;
      rw        : IN     STD_LOGIC;
      busy      : OUT    STD_LOGIC;
      data_rd   : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);
      scl       : INOUT  STD_LOGIC;
      sda       : INOUT  STD_LOGIC;
      ack_error : BUFFER STD_LOGIC
   );
   END COMPONENT;
   COMPONENT i2s_transceiver
   GENERIC (
      mclk_sclk_ratio : INTEGER := 4;       --number of mclk periods per sclk period
      sclk_ws_ratio   : INTEGER := 64;      --number of sclk periods per word select period
      d_width         : INTEGER := 24
   );
   PORT (
      l_data_tx : IN     STD_LOGIC_VECTOR (d_width-1 DOWNTO 0);
      mclk      : IN     STD_LOGIC;
      r_data_tx : IN     STD_LOGIC_VECTOR (d_width-1 DOWNTO 0);
      reset_n   : IN     STD_LOGIC;
      sd_rx     : IN     STD_LOGIC;
      l_data_rx : OUT    STD_LOGIC_VECTOR (d_width-1 DOWNTO 0);
      r_data_rx : OUT    STD_LOGIC_VECTOR (d_width-1 DOWNTO 0);
      sclk      : OUT    STD_LOGIC;
      sd_tx     : OUT    STD_LOGIC;
      ws        : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT pll5012new
   PORT (
      refclk   : IN     std_logic  := '0';
      rst      : IN     std_logic  := '0';
      outclk_0 : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT taktteiler
   GENERIC (
      MAX : integer := 2
   );
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic ;
      tick  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT testsoundctrl
   PORT (
      clk         : IN     std_logic ;
      ready       : IN     STD_LOGIC ;
      res_n       : IN     std_logic ;
      sampletick  : IN     std_logic ;
      voltick     : IN     std_logic ;
      l_data_tx   : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      leftadcvol  : OUT    STD_LOGIC_VECTOR (5 DOWNTO 0);
      leftdacvol  : OUT    STD_LOGIC_VECTOR (6 DOWNTO 0);
      r_data_tx   : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      rightadcvol : OUT    STD_LOGIC_VECTOR (5 DOWNTO 0);
      rightdacvol : OUT    STD_LOGIC_VECTOR (6 DOWNTO 0);
      update      : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : SSM2603regwriter USE ENTITY audiotest_lib.SSM2603regwriter;
   FOR ALL : codecsetup USE ENTITY audiotest_lib.codecsetup;
   FOR ALL : i2c_master USE ENTITY audiotest_lib.i2c_master;
   FOR ALL : i2s_transceiver USE ENTITY audiotest_lib.i2s_transceiver;
   FOR ALL : pll5012new USE ENTITY audiotest_lib.pll5012new;
   FOR ALL : taktteiler USE ENTITY audiotest_lib.taktteiler;
   FOR ALL : testsoundctrl USE ENTITY audiotest_lib.testsoundctrl;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 2 eb2
   -- eb1 1
   res <= not res_n; 
   sd_rx <= '0';                                      


   -- Instance port mappings.
   U_2 : SSM2603regwriter
      PORT MAP (
         I2Cbusy   => busy,
         clk       => clk,
         regaddr   => regaddr,
         regdata   => regdata,
         res_n     => res_n,
         setreg    => I2Cstarttransfer,
         addr      => addr,
         data_wr   => data_wr,
         ena       => ena,
         rw        => rw1,
         writedone => writedone
      );
   U_7 : codecsetup
      PORT MAP (
         ack_error        => ack_error_internal,
         clk              => clk,
         leftadcvol       => leftadcvol,
         leftdacvol       => leftdacvol,
         res_n            => res_n,
         rightadcvol      => rightadcvol,
         rightdacvol      => rightdacvol,
         update           => update,
         writedone        => writedone,
         I2Cstarttransfer => I2Cstarttransfer,
         error            => error,
         ready            => ready,
         regaddr          => regaddr,
         regdata          => regdata
      );
   U_0 : i2c_master
      GENERIC MAP (
         input_clk => 50_000_000,         --input clock speed from user logic in Hz
         bus_clk   => 100_000
      )
      PORT MAP (
         clk       => clk,
         reset_n   => res_n,
         ena       => ena,
         addr      => addr,
         rw        => rw1,
         data_wr   => data_wr,
         busy      => busy,
         data_rd   => OPEN,
         ack_error => ack_error_internal,
         sda       => SSM2603_sda,
         scl       => SSM2603_scl
      );
   U_1 : i2s_transceiver
      GENERIC MAP (
         mclk_sclk_ratio => 4,          --number of mclk periods per sclk period
         sclk_ws_ratio   => 64,         --number of sclk periods per word select period
         d_width         => 16
      )
      PORT MAP (
         reset_n   => res_n,
         mclk      => SSM2603_cclk_internal,
         sclk      => SSM2603_bclk,
         ws        => SSM2603_pblrc,
         sd_tx     => SSM2603_pbdat,
         sd_rx     => sd_rx,
         l_data_tx => l_data_tx,
         r_data_tx => r_data_tx,
         l_data_rx => OPEN,
         r_data_rx => OPEN
      );
   U_5 : pll5012new
      PORT MAP (
         refclk   => clk,
         rst      => res,
         outclk_0 => SSM2603_cclk_internal
      );
   U_4 : taktteiler
      GENERIC MAP (
         MAX => 3
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         tick  => sampletick
      );
   U_6 : taktteiler
      GENERIC MAP (
         MAX => 10_000_000
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         tick  => voltick
      );
   U_3 : testsoundctrl
      PORT MAP (
         clk         => clk,
         ready       => ready,
         res_n       => res_n,
         sampletick  => sampletick,
         voltick     => voltick,
         l_data_tx   => l_data_tx,
         leftadcvol  => leftadcvol,
         leftdacvol  => leftdacvol,
         r_data_tx   => r_data_tx,
         rightadcvol => rightadcvol,
         rightdacvol => rightdacvol,
         update      => update
      );

   -- Implicit buffered output assignments
   SSM2603_cclk <= SSM2603_cclk_internal;
   ack_error    <= ack_error_internal;

END struct;
