-- VHDL Entity audiotest_lib.bankswitcher.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:47:37 02/20/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib;
use audiotest_lib.booleanvectors.all;

ENTITY bankswitcher IS
   PORT( 
      clk      : IN     std_logic;
      confaddr : IN     boolean_vector (3 DOWNTO 0);
      confdata : IN     boolean_vector (7 DOWNTO 0);
      res_n    : IN     std_logic;
      virtaddr : IN     boolean_vector (14 DOWNTO 0);
      wr       : IN     boolean;
      physaddr : OUT    boolean_vector (23 DOWNTO 0)
   );

-- Declarations

END bankswitcher ;

