-- VHDL Entity audiotest_lib.bytemux1.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:43:54 02/20/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY bytemux1 IS
   PORT( 
      addr    : IN     boolean_vector (23 DOWNTO 0);
      qw      : IN     STD_LOGIC_VECTOR (63 DOWNTO 0);
      address : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      q       : OUT    boolean_vector (7 DOWNTO 0)
   );

-- Declarations

END bytemux1 ;

