-- VHDL Entity audiotest_lib.clkresstdlogic2bool.symbol
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 13:17:08 01/08/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY clkresstdlogic2bool IS
   PORT( 
      clkstdlog  : IN     std_logic;
      resnstdlog : IN     std_logic;
      clk        : OUT    boolean;
      res_n      : OUT    boolean
   );

-- Declarations

END clkresstdlogic2bool ;

