-- VHDL Entity audiotest_lib.codeccontroller.interface
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 13:27:47 12/14/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.numeric_std.all;
LIBRARY altera_lnsim;
USE altera_lnsim.altera_lnsim_components.all;
LIBRARY altera_mf; USE altera_mf.altera_mf_components.all;
USE ieee.std_logic_unsigned.all;

ENTITY codeccontroller IS
-- Declarations

END codeccontroller ;

