-- VHDL Entity audiotest_lib.controlPort.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:49:48 02/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;
USE ieee.math_real.all;
USE ieee.numeric_std.all;

ENTITY controlPort IS
   PORT( 
      clk           : IN     std_logic;
      controlportrd : IN     boolean;
      controlportwr : IN     boolean;
      cpuclk        : IN     boolean;
      res_n         : IN     std_logic;
      resetCPU      : IN     boolean;
      runCPU        : IN     boolean;
      selectedSong  : IN     boolean_vector (7 DOWNTO 0);
      cpuRES        : OUT    std_logic;
      status        : OUT    boolean_vector (7 DOWNTO 0);
      tickCPU       : OUT    boolean;
      data          : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END controlPort ;

