-- VHDL Entity audiotest_lib.dmcchannnel.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:35:36 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY dmcchannnel IS
   PORT( 
      addr          : IN     boolean_vector (1 DOWNTO 0);
      clearintflag  : IN     boolean;
      clk           : IN     std_logic;
      cpuclk        : IN     boolean;
      data          : IN     boolean_vector (7 DOWNTO 0);
      dmcdata       : IN     boolean_vector (7 DOWNTO 0);
      dmcreadack    : IN     boolean;
      enabled       : IN     boolean;
      res_n         : IN     std_logic;
      wr            : IN     boolean;
      dmcaddr       : OUT    boolean_vector (15 DOWNTO 0);
      dmcreadreq    : OUT    boolean;
      irq           : OUT    boolean;
      level         : OUT    boolean_vector (6 DOWNTO 0);
      playingsample : OUT    boolean
   );

-- Declarations

END dmcchannnel ;

