-- VHDL Entity audiotest_lib.dmcoutputlevel.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:36:04 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY dmcoutputlevel IS
   PORT( 
      clk       : IN     std_logic;
      cpuclk    : IN     boolean;
      decLevel  : IN     boolean;
      incLevel  : IN     boolean;
      loadval   : IN     boolean_vector (6 DOWNTO 0);
      loadvalue : IN     boolean;
      res_n     : IN     std_logic;
      level     : OUT    boolean_vector (6 DOWNTO 0)
   );

-- Declarations

END dmcoutputlevel ;

