-- VHDL Entity audiotest_lib.dmcsampleshifter.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 13:12:47 03/11/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY dmcsampleshifter IS
   GENERIC( 
      reversesamplebyte : boolean := false
   );
   PORT( 
      clk            : IN     std_logic;
      cpuclk         : IN     boolean;
      playsample     : IN     boolean;
      res_n          : IN     std_logic;
      sample         : IN     boolean_vector (7 DOWNTO 0);
      tick           : IN     boolean;
      decLevel       : OUT    boolean;
      halfsampledone : OUT    boolean;
      incLevel       : OUT    boolean;
      sampledone     : OUT    boolean
   );

-- Declarations

END dmcsampleshifter ;

