--
-- VHDL Architecture audiotest_lib.dmcTB.struct
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 16:26:54 01/23/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY audiotest_lib;

ARCHITECTURE struct OF dmcTB IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL addr          : boolean_vector(1 DOWNTO 0);
   SIGNAL cleaintflag   : boolean;
   SIGNAL clearintflag  : boolean;
   SIGNAL clk           : std_logic;
   SIGNAL cpuclk        : boolean;
   SIGNAL data          : boolean_vector(7 DOWNTO 0);
   SIGNAL dmcaddr       : boolean_vector(15 DOWNTO 0);
   SIGNAL dmcdata       : boolean_vector(7 DOWNTO 0);
   SIGNAL dmcreadack    : boolean;
   SIGNAL dmcreadreq    : boolean;
   SIGNAL enabled       : boolean;
   SIGNAL irq           : boolean;
   SIGNAL level         : boolean_vector(6 DOWNTO 0);
   SIGNAL playingsample : boolean;
   SIGNAL res_n         : std_logic;
   SIGNAL wr            : boolean;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT dmcTBctrl
   PORT (
      clk     : IN     std_logic ;
      cpuclk  : IN     boolean ;
      irq     : IN     boolean ;
      res_n   : IN     std_logic ;
      addr    : OUT    boolean_vector (1 DOWNTO 0);
      data    : OUT    boolean_vector (7 DOWNTO 0);
      enabled : OUT    boolean ;
      wr      : OUT    boolean 
   );
   END COMPONENT;
   COMPONENT dmcchannnel
   PORT (
      addr          : IN     boolean_vector (1 DOWNTO 0);
      cleaintflag   : IN     boolean ;
      clearintflag  : IN     boolean ;
      clk           : IN     std_logic ;
      cpuclk        : IN     boolean ;
      data          : IN     boolean_vector (7 DOWNTO 0);
      dmcdata       : IN     boolean_vector (7 DOWNTO 0);
      dmcreadack    : IN     boolean ;
      enabled       : IN     boolean ;
      res_n         : IN     std_logic ;
      wr            : IN     boolean ;
      dmcaddr       : OUT    boolean_vector (15 DOWNTO 0);
      dmcreadreq    : OUT    boolean ;
      irq           : OUT    boolean ;
      level         : OUT    boolean_vector (6 DOWNTO 0);
      playingsample : OUT    boolean 
   );
   END COMPONENT;
   COMPONENT dmctestrom
   PORT (
      clk        : IN     std_logic ;
      dmcaddr    : IN     boolean_vector (15 DOWNTO 0);
      dmcreadreq : IN     boolean ;
      res_n      : IN     std_logic ;
      dmcdata    : OUT    boolean_vector (7 DOWNTO 0);
      dmcreadack : OUT    boolean 
   );
   END COMPONENT;
   COMPONENT taktteilerboolean
   GENERIC (
      MAX : integer := 30
   );
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic ;
      tick  : OUT    boolean 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY audiotest_lib.clk_res_gen;
   FOR ALL : dmcTBctrl USE ENTITY audiotest_lib.dmcTBctrl;
   FOR ALL : dmcchannnel USE ENTITY audiotest_lib.dmcchannnel;
   FOR ALL : dmctestrom USE ENTITY audiotest_lib.dmctestrom;
   FOR ALL : taktteilerboolean USE ENTITY audiotest_lib.taktteilerboolean;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   tbctrl : dmcTBctrl
      PORT MAP (
         clk     => clk,
         cpuclk  => cpuclk,
         irq     => irq,
         res_n   => res_n,
         addr    => addr,
         data    => data,
         enabled => enabled,
         wr      => wr
      );
   U_1 : dmcchannnel
      PORT MAP (
         addr          => addr,
         cleaintflag   => cleaintflag,
         clearintflag  => clearintflag,
         clk           => clk,
         cpuclk        => cpuclk,
         data          => data,
         dmcdata       => dmcdata,
         dmcreadack    => dmcreadack,
         enabled       => enabled,
         res_n         => res_n,
         wr            => wr,
         dmcaddr       => dmcaddr,
         dmcreadreq    => dmcreadreq,
         irq           => irq,
         level         => level,
         playingsample => playingsample
      );
   tstrom : dmctestrom
      PORT MAP (
         clk        => clk,
         dmcaddr    => dmcaddr,
         dmcreadreq => dmcreadreq,
         res_n      => res_n,
         dmcdata    => dmcdata,
         dmcreadack => dmcreadack
      );
   U_5 : taktteilerboolean
      GENERIC MAP (
         MAX => 30
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         tick  => cpuclk
      );

END struct;
