-- VHDL Entity audiotest_lib.dmctestrom.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 12:18:54 01/23/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY dmctestrom IS
   PORT( 
      clk        : IN     std_logic;
      dmcaddr    : IN     boolean_vector (15 DOWNTO 0);
      dmcreadreq : IN     boolean;
      res_n      : IN     std_logic;
      dmcdata    : OUT    boolean_vector (7 DOWNTO 0);
      dmcreadack : OUT    boolean
   );

-- Declarations

END dmctestrom ;

