-- VHDL Entity audiotest_lib.dmcTBctrl.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 16:26:54 01/23/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY dmcTBctrl IS
   PORT( 
      clk     : IN     std_logic;
      cpuclk  : IN     boolean;
      irq     : IN     boolean;
      res_n   : IN     std_logic;
      addr    : OUT    boolean_vector (1 DOWNTO 0);
      data    : OUT    boolean_vector (7 DOWNTO 0);
      enabled : OUT    boolean;
      wr      : OUT    boolean
   );

-- Declarations

END dmcTBctrl ;

