-- VHDL Entity audiotest_lib.dmcTB.symbol
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 14:59:34 01/17/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;


ENTITY dmcTB IS
-- Declarations

END dmcTB ;

