-- VHDL Entity audiotest_lib.dmcwriteport.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:36:04 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY dmcwriteport IS
   PORT( 
      addr                  : IN     boolean_vector (1 DOWNTO 0);
      clearintflag          : IN     boolean;
      clk                   : IN     std_logic;
      data                  : IN     boolean_vector (7 DOWNTO 0);
      enabled               : IN     boolean;
      playbackdone          : IN     boolean;
      res_n                 : IN     std_logic;
      wr                    : IN     boolean;
      enableplayback        : OUT    boolean;
      irq                   : OUT    boolean;
      loadcurrentaddrandlen : OUT    boolean;
      loadval               : OUT    boolean_vector (6 DOWNTO 0);
      loadvalue             : OUT    boolean;
      loopenable            : OUT    boolean;
      periodsetting         : OUT    boolean_vector (3 DOWNTO 0);
      playingsample         : OUT    boolean;
      sampleencaddr         : OUT    boolean_vector (7 DOWNTO 0);
      sampleenclength       : OUT    boolean_vector (7 DOWNTO 0);
      updateperiod          : OUT    boolean
   );

-- Declarations

END dmcwriteport ;

