-- VHDL Entity audiotest_lib.entireNESTB.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 13:14:22 02/05/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;


ENTITY entireNESTB IS
-- Declarations

END entireNESTB ;

