-- VHDL Entity audiotest_lib.entireNES.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 11:31:18 03/13/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY entireNES IS
   PORT( 
      clk          : IN     std_logic;
      clk1M        : IN     std_logic;
      res_n        : IN     std_logic;
      resetCPU     : IN     boolean;
      runCPU       : IN     boolean;
      selectedSong : IN     boolean_vector (7 DOWNTO 0);
      mix          : OUT    boolean_vector (11 DOWNTO 0);
      status       : OUT    boolean_vector (7 DOWNTO 0)
   );

-- Declarations

END entireNES ;

