--
-- VHDL Architecture audiotest_lib.entireNESTB.struct
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 15:34:06 03/11/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;


ARCHITECTURE struct OF entireNESTB IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk          : std_logic;
   SIGNAL clk1         : std_logic;
   SIGNAL mix          : boolean_vector(11 DOWNTO 0);
   SIGNAL res_n        : std_logic;
   SIGNAL resetCPU     : boolean;
   SIGNAL runCPU       : boolean;
   SIGNAL selectedSong : boolean_vector(7 DOWNTO 0);
   SIGNAL status       : boolean_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT clk_res_gen_var
   GENERIC (
      ONTIME    : time := 10 ns;
      OFFTIME   : time := 10 ns;
      RESETTIME : time := 35 ns
   );
   PORT (
      clk   : OUT    std_logic ;
      res_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT entireNES
   PORT (
      clk          : IN     std_logic ;
      clk1M        : IN     std_logic ;
      res_n        : IN     std_logic ;
      resetCPU     : IN     boolean ;
      runCPU       : IN     boolean ;
      selectedSong : IN     boolean_vector (7 DOWNTO 0);
      mix          : OUT    boolean_vector (11 DOWNTO 0);
      status       : OUT    boolean_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT sndgrabber
   PORT (
      mix : IN     boolean_vector (11 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen_var USE ENTITY audiotest_lib.clk_res_gen_var;
   FOR ALL : entireNES USE ENTITY audiotest_lib.entireNES;
   FOR ALL : sndgrabber USE ENTITY audiotest_lib.sndgrabber;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1 
   resetCPU <= false;
   runCPU <= true;
   selectedSong <= (others => false);                                       


   -- Instance port mappings.
   U_3 : clk_res_gen_var
      GENERIC MAP (
         ONTIME    => 37.6 ns,
         OFFTIME   => 37.6 ns,
         RESETTIME => 35 ns
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   U_4 : clk_res_gen_var
      GENERIC MAP (
         ONTIME    => 500 ns,
         OFFTIME   => 500 ns,
         RESETTIME => 35 ns
      )
      PORT MAP (
         clk   => clk1,
         res_n => OPEN
      );
   enes : entireNES
      PORT MAP (
         clk          => clk,
         clk1M        => clk1,
         res_n        => res_n,
         resetCPU     => resetCPU,
         runCPU       => runCPU,
         selectedSong => selectedSong,
         mix          => mix,
         status       => status
      );
   U_2 : sndgrabber
      PORT MAP (
         mix => mix
      );

END struct;
