-- VHDL Entity audiotest_lib.initialisableRAM.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 15:52:29 01/29/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib;
use audiotest_lib.booleanvectors.all;

ENTITY initialisableRAM IS
   GENERIC( 
      addrw : integer := 2;
      dataw : integer := 8
   );
   PORT( 
      addr  : IN     boolean_vector (addrw-1 DOWNTO 0);
      clk   : IN     std_logic;
      d     : IN     boolean_vector (dataw-1 DOWNTO 0);
      res_n : IN     std_logic;
      wr    : IN     boolean;
      q     : OUT    boolean_vector (dataw-1 DOWNTO 0)
   );

-- Declarations

END initialisableRAM ;

