-- VHDL Entity audiotest_lib.memarbitermx65interface.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:49:48 02/14/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;
USE ieee.math_real.all;
USE ieee.numeric_std.all;

ENTITY memarbitermx65interface IS
   GENERIC( 
      addrw : integer := 16;
      dataw : integer := 8
   );
   PORT( 
      clk                : IN     std_logic;
      cpu_addr           : IN     std_logic_vector (15 DOWNTO 0);
      cpu_data_out       : IN     std_logic_vector (7 DOWNTO 0);
      cpuportackread     : IN     boolean;
      cpuportackwrite    : IN     boolean;
      cpuportdatatodev   : IN     boolean_vector (7 DOWNTO 0);
      res_n              : IN     std_logic;
      rw                 : IN     std_logic;
      sync               : IN     std_logic;
      tickCPU            : IN     boolean;
      cpu_data_in        : OUT    std_logic_vector (7 DOWNTO 0);
      cpuportaddr        : OUT    boolean_vector (15 DOWNTO 0);
      cpuportdatafromdev : OUT    boolean_vector (7 DOWNTO 0);
      cpuportreqread     : OUT    boolean;
      cpuportreqwrite    : OUT    boolean;
      tick               : OUT    std_logic
   );

-- Declarations

END memarbitermx65interface ;

