-- VHDL Entity audiotest_lib.memorieswrapper.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 12:36:29 03/11/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY memorieswrapper IS
   PORT( 
      addr           : IN     boolean_vector (15 DOWNTO 0);
      bkswwr         : IN     boolean;
      clk            : IN     std_logic;
      overlayvectors : IN     boolean;
      rd             : IN     boolean;
      res_n          : IN     std_logic;
      vectorramwr    : IN     boolean;
      wr             : IN     boolean;
      accesswait     : OUT    std_logic;
      data           : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END memorieswrapper ;

