-- VHDL Entity audiotest_lib.namco163dev.generatedInstance
--
-- Created:
--          by - redacted.redacted (pc038)
--          at - 10:04:19 02/08/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY namco163dev IS
END namco163dev ;

