-- VHDL Entity audiotest_lib.namco163tbctrl.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 11:09:20 02/19/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.numeric_std.all;

ENTITY namco163tbctrl IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      tick  : IN     boolean;
      addr  : OUT    boolean_vector (1 DOWNTO 0);
      rd    : OUT    boolean;
      wr    : OUT    boolean;
      data  : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END namco163tbctrl ;

