-- VHDL Entity audiotest_lib.namco163writeport.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:06:58 02/15/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY namco163writeport IS
   PORT( 
      addr           : IN     boolean_vector (1 DOWNTO 0);
      clk            : IN     std_logic;
      rd             : IN     boolean;
      res_n          : IN     std_logic;
      wpdataout      : IN     boolean_vector (7 DOWNTO 0);
      wr             : IN     boolean;
      activechannels : OUT    integer RANGE 1 TO 8;
      enableFSM      : OUT    boolean;
      wpaddr         : OUT    boolean_vector (6 DOWNTO 0);
      wpdatain       : OUT    boolean_vector (7 DOWNTO 0);
      wpwren         : OUT    boolean;
      data           : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END namco163writeport ;

