-- VHDL Entity audiotest_lib.namco163statemachine.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 16:28:03 02/19/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY namco163statemachine IS
   GENERIC( 
      USETDM : boolean := false
   );
   PORT( 
      activechannels : IN     integer RANGE 1 TO 8;
      clk            : IN     std_logic;
      cpuclk         : IN     boolean;
      enableFSM      : IN     boolean;
      ramdataout     : IN     boolean_vector (7 DOWNTO 0);
      res_n          : IN     std_logic;
      n163mix        : OUT    boolean_vector (7 DOWNTO 0);
      ramdatain      : OUT    boolean_vector (7 DOWNTO 0);
      ramwr          : OUT    boolean;
      wram_address   : OUT    boolean_vector (6 DOWNTO 0)
   );

-- Declarations

END namco163statemachine ;

