-- VHDL Entity audiotest_lib.namco163.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 13:16:51 02/20/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY namco163 IS
   GENERIC( 
      USETDM : boolean := true
   );
   PORT( 
      addr    : IN     boolean_vector (1 DOWNTO 0);
      clk     : IN     std_logic;
      cpuclk  : IN     boolean;
      rd      : IN     boolean;
      res_n   : IN     std_logic;
      wr      : IN     boolean;
      n163mix : OUT    boolean_vector (7 DOWNTO 0);
      data    : INOUT  std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END namco163 ;

