-- VHDL Entity audiotest_lib.namco163tb.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:33:09 02/19/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;


ENTITY namco163tb IS
-- Declarations

END namco163tb ;

