-- VHDL Entity audiotest_lib.nesmixer.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:04:03 03/13/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;
USE ieee.math_real.all;
USE ieee.numeric_std.all;

ENTITY nesmixer IS
   PORT( 
      apumix  : IN     boolean_vector (7 DOWNTO 0);
      clk     : IN     std_logic;
      n163mix : IN     boolean_vector (7 DOWNTO 0);
      res_n   : IN     std_logic;
      vrc6mix : IN     boolean_vector (5 DOWNTO 0);
      mix     : OUT    boolean_vector (11 DOWNTO 0)
   );

-- Declarations

END nesmixer ;

