--
-- VHDL Architecture audiotest_lib.NEStoplevelTB.struct
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 13:08:50 02/05/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY audiotest_lib;

ARCHITECTURE struct OF NEStoplevelTB IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL res_n : std_logic;


   -- Component Declarations
   COMPONENT NESPlayertoplevel
   PORT (
      clk           : IN     std_logic ;
      res_n         : IN     std_logic ;
      SSM2603_bclk  : OUT    STD_LOGIC ;
      SSM2603_cclk  : OUT    STD_LOGIC ;
      SSM2603_pbdat : OUT    STD_LOGIC ;
      SSM2603_pblrc : OUT    STD_LOGIC ;
      ack_error     : OUT    STD_LOGIC ;
      cpurunstd     : OUT    std_logic ;
      SSM2603_scl   : INOUT  STD_LOGIC ;
      SSM2603_sda   : INOUT  STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : NESPlayertoplevel USE ENTITY audiotest_lib.NESPlayertoplevel;
   FOR ALL : clk_res_gen USE ENTITY audiotest_lib.clk_res_gen;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : NESPlayertoplevel
      PORT MAP (
         clk           => clk,
         res_n         => res_n,
         SSM2603_bclk  => OPEN,
         SSM2603_cclk  => OPEN,
         SSM2603_pbdat => OPEN,
         SSM2603_pblrc => OPEN,
         ack_error     => OPEN,
         cpurunstd     => OPEN,
         SSM2603_scl   => OPEN,
         SSM2603_sda   => OPEN
      );
   U_1 : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );

END struct;
