-- VHDL Entity audiotest_lib.noiseTB.symbol
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 11:12:34 01/17/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;


ENTITY noiseTB IS
-- Declarations

END noiseTB ;

