-- VHDL Entity audiotest_lib.NoiseLFSR1.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:17:02 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY NoiseLFSR1 IS
   PORT( 
      clk          : IN     std_logic;
      cpuclk       : IN     boolean;
      res_n        : IN     std_logic;
      tick         : IN     boolean;
      usebit6forfb : IN     boolean;
      bit0         : OUT    boolean
   );

-- Declarations

END NoiseLFSR1 ;

