-- VHDL Entity audiotest_lib.premixer.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:18:41 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY premixer IS
   PORT( 
      mute1  : IN     boolean;
      mute2  : IN     boolean;
      mute3  : IN     boolean;
      q      : IN     boolean;
      volume : IN     boolean_vector (3 DOWNTO 0);
      mixed  : OUT    boolean_vector (3 DOWNTO 0)
   );

-- Declarations

END premixer ;

