-- VHDL Entity audiotest_lib.psweep.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:20:13 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
--USE ieee.std_logic_arith.all;
--USE IEEE.numeric_std.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY psweep IS
   GENERIC( 
      SUBOFFSET : integer := 0
   );
   PORT( 
      clk             : IN     std_logic;
      hfclk           : IN     boolean;
      loadperiod      : IN     boolean;
      period          : IN     boolean_vector (10 DOWNTO 0);
      pulsetimerq     : IN     boolean_vector (10 DOWNTO 0);
      res_n           : IN     std_logic;
      sweepen         : IN     boolean;
      sweepnegate     : IN     boolean;
      sweepreload     : IN     boolean;
      sweepshcnt      : IN     boolean_vector (2 DOWNTO 0);
      sweeptickperiod : IN     boolean_vector (2 DOWNTO 0);
      cperiod         : OUT    boolean_vector (10 DOWNTO 0);
      mutingMix       : OUT    boolean
   );

-- Declarations

END psweep ;

