-- VHDL Entity audiotest_lib.pulsedividersequence.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:20:13 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
--USE ieee.std_logic_arith.all;
--USE IEEE.numeric_std.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY pulsedividersequence IS
   PORT( 
      apuclk          : IN     boolean;
      clk             : IN     std_logic;
      cperiod         : IN     boolean_vector (10 DOWNTO 0);
      pulseduty       : IN     boolean_vector (1 DOWNTO 0);
      res_n           : IN     std_logic;
      restartsequence : IN     boolean;
      pulsetimerq     : OUT    boolean_vector (10 DOWNTO 0);
      q               : OUT    boolean
   );

-- Declarations

END pulsedividersequence ;

