-- VHDL Entity audiotest_lib.pulseenv.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:17:58 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
--USE ieee.std_logic_arith.all;
--USE IEEE.numeric_std.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY pulseenv IS
   PORT( 
      clk          : IN     std_logic;
      constvol     : IN     boolean;
      loopenvelope : IN     boolean;
      qfclk        : IN     boolean;
      res_n        : IN     std_logic;
      restartenv   : IN     boolean;
      startenv     : IN     boolean;
      volumeset    : IN     boolean_vector (3 DOWNTO 0);
      volume       : OUT    boolean_vector (3 DOWNTO 0)
   );

-- Declarations

END pulseenv ;

