-- VHDL Entity audiotest_lib.pulseenv1.generatedInstance
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 14:22:04 01/17/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY pulseenv1 IS
   PORT( 
      clk          : IN     std_logic;
      constvol     : IN     boolean;
      loopenvelope : IN     boolean;
      qfclk        : IN     boolean;
      res_n        : IN     std_logic;
      restartenv   : IN     boolean;
      startenv     : IN     boolean;
      volume       : OUT    boolean_vector (3 DOWNTO 0);
      volumeset    : IN     boolean_vector (3 DOWNTO 0)
   );

END pulseenv1 ;

