-- VHDL Entity audiotest_lib.sndgrabber.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 13:28:00 02/20/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY sndgrabber IS
   PORT( 
      mix : IN     boolean_vector (11 DOWNTO 0)
   );

-- Declarations

END sndgrabber ;

