-- VHDL Entity audiotest_lib.SSM2603regwriter.symbol
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 13:34:49 12/14/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.numeric_std.all;
LIBRARY altera_lnsim;
USE altera_lnsim.altera_lnsim_components.all;
LIBRARY altera_mf; USE altera_mf.altera_mf_components.all;
USE ieee.std_logic_unsigned.all;

ENTITY SSM2603regwriter IS
   PORT( 
      I2Cbusy   : IN     std_logic;
      clk       : IN     std_logic;
      regaddr   : IN     std_logic_vector (6 DOWNTO 0);
      regdata   : IN     std_logic_vector (8 DOWNTO 0);
      res_n     : IN     std_logic;
      setreg    : IN     std_logic;
      addr      : OUT    std_logic_vector (6 DOWNTO 0);
      data_wr   : OUT    std_logic_vector (7 DOWNTO 0);
      ena       : OUT    std_logic;
      rw        : OUT    std_logic;
      writedone : OUT    std_logic
   );

-- Declarations

END SSM2603regwriter ;

