-- VHDL Entity audiotest_lib.taktteilerboolean.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 11:00:23 02/19/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.numeric_std.all;

ENTITY taktteilerboolean IS
   GENERIC( 
      MAX : integer := 8
   );
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      tick  : OUT    boolean
   );

-- Declarations

END taktteilerboolean ;

