-- VHDL Entity audiotest_lib.taktteiler.symbol
--
-- Created:
--          by - redacted.redacted (pc038)
--          at - 16:50:25 12/11/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE IEEE.numeric_std.all;

ENTITY taktteiler IS
   GENERIC( 
      MAX : integer := 2
   );
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      tick  : OUT    std_logic
   );

-- Declarations

END taktteiler ;

