-- VHDL Entity audiotest_lib.testsoundctrl1.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 13:49:57 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY testsoundctrl1 IS
   PORT( 
      clk         : IN     std_logic;
      mix         : IN     boolean_vector (7 DOWNTO 0);
      ready       : IN     STD_LOGIC;
      res_n       : IN     std_logic;
      l_data_tx   : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      leftadcvol  : OUT    STD_LOGIC_VECTOR (5 DOWNTO 0);
      leftdacvol  : OUT    STD_LOGIC_VECTOR (6 DOWNTO 0);
      r_data_tx   : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      resetCPU    : OUT    boolean;
      rightadcvol : OUT    STD_LOGIC_VECTOR (5 DOWNTO 0);
      rightdacvol : OUT    STD_LOGIC_VECTOR (6 DOWNTO 0);
      runCPU      : OUT    boolean;
      update      : OUT    STD_LOGIC
   );

-- Declarations

END testsoundctrl1 ;

