-- VHDL Entity audiotest_lib.toplevelcontrol.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 10:09:13 03/15/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;
LIBRARY altera_lnsim;
USE altera_lnsim.altera_lnsim_components.all;

ENTITY toplevelcontrol IS
   GENERIC( 
      monoaudio : boolean := false
   );
   PORT( 
      cpuclkx8    : IN     std_logic;
      mix         : IN     boolean_vector (11 DOWNTO 0);
      ready       : IN     STD_LOGIC;
      res_n       : IN     std_logic;
      l_data_tx   : OUT    std_logic_vector (15 DOWNTO 0);
      leftadcvol  : OUT    STD_LOGIC_VECTOR (5 DOWNTO 0);
      leftdacvol  : OUT    STD_LOGIC_VECTOR (6 DOWNTO 0);
      r_data_tx   : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      resetCPU    : OUT    boolean;
      rightadcvol : OUT    STD_LOGIC_VECTOR (5 DOWNTO 0);
      rightdacvol : OUT    STD_LOGIC_VECTOR (6 DOWNTO 0);
      runCPU      : OUT    boolean;
      update      : OUT    STD_LOGIC
   );

-- Declarations

END toplevelcontrol ;

