-- VHDL Entity audiotest_lib.triangleTBctrl.interface
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 15:47:07 01/16/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY triangleTBctrl IS
   PORT( 
      apuclk : IN     boolean;
      clk    : IN     std_logic;
      res_n  : IN     std_logic;
      addr   : OUT    integer RANGE 0 TO 3;
      data   : OUT    boolean_vector (7 DOWNTO 0);
      genint : OUT    boolean;
      mode   : OUT    boolean;
      resctr : OUT    boolean;
      wr     : OUT    boolean
   );

-- Declarations

END triangleTBctrl ;

