-- VHDL Entity audiotest_lib.trianglewriteport.interface
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:34:32 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY trianglewriteport IS
   PORT( 
      addr         : IN     boolean_vector (1 DOWNTO 0);
      clk          : IN     std_logic;
      data         : IN     boolean_vector (7 DOWNTO 0);
      enabled      : IN     boolean;
      res_n        : IN     std_logic;
      wr           : IN     boolean;
      length       : OUT    boolean_vector (4 DOWNTO 0);
      lengthctren  : OUT    boolean;
      linearctrl   : OUT    boolean;
      linearreload : OUT    boolean;
      mute1        : OUT    boolean;
      period       : OUT    boolean_vector (10 DOWNTO 0);
      reloadval    : OUT    boolean_vector (6 DOWNTO 0);
      wrlength     : OUT    boolean
   );

-- Declarations

END trianglewriteport ;

