-- VHDL Entity audiotest_lib.trianglechannel.symbol
--
-- Created:
--          by - redacted.redacted (pc023)
--          at - 14:33:48 02/02/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
library audiotest_lib; use audiotest_lib.booleanvectors.all;

ENTITY trianglechannel IS
   PORT( 
      addr    : IN     boolean_vector (1 DOWNTO 0);
      apuclk  : IN     boolean;
      clk     : IN     std_logic;
      cpuclk  : IN     boolean;
      data    : IN     boolean_vector (7 DOWNTO 0);
      enabled : IN     boolean;
      fclk    : IN     boolean;
      hfclk   : IN     boolean;
      qfclk   : IN     boolean;
      res_n   : IN     std_logic;
      wr      : IN     boolean;
      iszero  : OUT    boolean;
      mixed   : OUT    boolean_vector (3 DOWNTO 0)
   );

-- Declarations

END trianglechannel ;

