--
-- VHDL Architecture audiotest_lib.triangleTB.struct
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 16:16:21 01/16/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY audiotest_lib;

ARCHITECTURE struct OF triangleTB IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL addr   : integer RANGE 0 TO 3;
   SIGNAL apuclk : boolean;
   SIGNAL clk    : std_logic;
   SIGNAL cpuclk : boolean;
   SIGNAL data   : boolean_vector(7 DOWNTO 0);
   SIGNAL fclk   : boolean;
   SIGNAL genint : boolean;
   SIGNAL hfclk  : boolean;
   SIGNAL int    : boolean;
   SIGNAL mixed  : boolean_vector(3 DOWNTO 0);
   SIGNAL mode   : boolean;
   SIGNAL qfclk  : boolean;
   SIGNAL res_n  : std_logic;
   SIGNAL resctr : boolean;
   SIGNAL wr     : boolean;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT framectr
   PORT (
      apuclk : IN     boolean ;
      clk    : IN     std_logic ;
      genint : IN     boolean ;
      mode   : IN     boolean ;
      res_n  : IN     std_logic ;
      resctr : IN     boolean ;
      fclk   : OUT    boolean ;
      hfclk  : OUT    boolean ;
      int    : OUT    boolean ;
      qfclk  : OUT    boolean 
   );
   END COMPONENT;
   COMPONENT taktteilerboolean
   GENERIC (
      MAX : integer := 30
   );
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic ;
      tick  : OUT    boolean 
   );
   END COMPONENT;
   COMPONENT triangleTBctrl
   PORT (
      apuclk : IN     boolean ;
      clk    : IN     std_logic ;
      res_n  : IN     std_logic ;
      addr   : OUT    integer RANGE 0 TO 3;
      data   : OUT    boolean_vector (7 DOWNTO 0);
      genint : OUT    boolean ;
      mode   : OUT    boolean ;
      resctr : OUT    boolean ;
      wr     : OUT    boolean 
   );
   END COMPONENT;
   COMPONENT trianglechannel
   PORT (
      addr   : IN     integer RANGE 0 TO 3;
      apuclk : IN     boolean ;
      clk    : IN     std_logic ;
      cpuclk : IN     boolean ;
      data   : IN     boolean_vector (7 DOWNTO 0);
      fclk   : IN     boolean ;
      hfclk  : IN     boolean ;
      qfclk  : IN     boolean ;
      res_n  : IN     std_logic ;
      wr     : IN     boolean ;
      mixed  : OUT    boolean_vector (3 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY audiotest_lib.clk_res_gen;
   FOR ALL : framectr USE ENTITY audiotest_lib.framectr;
   FOR ALL : taktteilerboolean USE ENTITY audiotest_lib.taktteilerboolean;
   FOR ALL : triangleTBctrl USE ENTITY audiotest_lib.triangleTBctrl;
   FOR ALL : trianglechannel USE ENTITY audiotest_lib.trianglechannel;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   U_3 : framectr
      PORT MAP (
         apuclk => apuclk,
         clk    => clk,
         genint => genint,
         mode   => mode,
         res_n  => res_n,
         resctr => resctr,
         fclk   => fclk,
         hfclk  => hfclk,
         int    => int,
         qfclk  => qfclk
      );
   U_4 : taktteilerboolean
      GENERIC MAP (
         MAX => 60
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         tick  => apuclk
      );
   U_5 : taktteilerboolean
      GENERIC MAP (
         MAX => 30
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         tick  => cpuclk
      );
   U_2 : triangleTBctrl
      PORT MAP (
         apuclk => apuclk,
         clk    => clk,
         res_n  => res_n,
         addr   => addr,
         data   => data,
         genint => genint,
         mode   => mode,
         resctr => resctr,
         wr     => wr
      );
   U_0 : trianglechannel
      PORT MAP (
         addr   => addr,
         apuclk => apuclk,
         clk    => clk,
         cpuclk => cpuclk,
         data   => data,
         fclk   => fclk,
         hfclk  => hfclk,
         qfclk  => qfclk,
         res_n  => res_n,
         wr     => wr,
         mixed  => mixed
      );

END struct;
