-- VHDL Entity audiotest_lib.triangleTB.symbol
--
-- Created:
--          by - redacted.redacted (pc025)
--          at - 16:36:05 01/15/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;


ENTITY triangleTB IS
-- Declarations

END triangleTB ;

