-- VHDL Entity audiotest_lib.ttboolean.symbol
--
-- Created:
--          by - redacted.redacted (pc038)
--          at - 15:52:13 01/10/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
--LIBRARY ieee;
--USE ieee.std_logic_1164.all;
--USE ieee.std_logic_arith.all;
--USE IEEE.numeric_std.all;

ENTITY ttboolean IS
   GENERIC( 
      MAX : integer := 60
   );
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      tick  : OUT    boolean
   );

-- Declarations

END ttboolean ;

